name: Run Tests and Static Analysis

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          extensions: mbstring, pdo, pdo_mysql

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  phpunit:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Run PHPUnit Tests with Coverage
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Generate HTML Coverage Report
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --coverage-html=coverage/

  coveralls:
    name: Submit to Coveralls
    runs-on: ubuntu-latest
    needs: phpunit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Submit Coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml

  publish-coverage:
    name: Publish Coverage to GitHub Pages
    runs-on: ubuntu-latest
    needs: phpunit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Publish Coverage Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
